package com.jblosc2.jna;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ContextCparams extends Structure<ContextCparams, ContextCparams.ByValue, ContextCparams.ByReference > {
	public byte typesize;
	/** the type size (8) */
	public byte compcode;
	/** the compressor code (BLOSC_BLOSCLZ) */
	public byte clevel;
	/** the compression level (5) */
	public byte filtercode;
	/** the filter code (BLOSC_SHUFFLE) */
	public byte nthreads;
	/** the number of threads to use internally (1) */
	public int blocksize;
	/**
	 * the requested size of the compressed blocks (0; meaning automatic)<br>
	 * C type : blosc2_sheader*
	 */
	public Sheader.ByReference schunk;
	public ContextCparams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("typesize", "compcode", "clevel", "filtercode", "nthreads", "blocksize", "schunk");
	}
	/**
	 * @param compcode the type size (8)<br>
	 * @param clevel the compressor code (BLOSC_BLOSCLZ)<br>
	 * @param filtercode the compression level (5)<br>
	 * @param nthreads the filter code (BLOSC_SHUFFLE)<br>
	 * @param blocksize the number of threads to use internally (1)<br>
	 * @param schunk the requested size of the compressed blocks (0; meaning automatic)<br>
	 * C type : blosc2_sheader*
	 */
	public ContextCparams(byte typesize, byte compcode, byte clevel, byte filtercode, byte nthreads, int blocksize, Sheader.ByReference schunk) {
		super();
		this.typesize = typesize;
		this.compcode = compcode;
		this.clevel = clevel;
		this.filtercode = filtercode;
		this.nthreads = nthreads;
		this.blocksize = blocksize;
		this.schunk = schunk;
	}
	public ContextCparams(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected ContextCparams newInstance() { return new ContextCparams(); }
	public static ContextCparams[] newArray(int arrayLength) {
		return Structure.newArray(ContextCparams.class, arrayLength);
	}
	public static class ByReference extends ContextCparams implements Structure.ByReference {
		
	};
	public static class ByValue extends ContextCparams implements Structure.ByValue {
		
	};
}
