package com.jblosc2.jna;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ContextDparams extends Structure<ContextDparams, ContextDparams.ByValue, ContextDparams.ByReference > {
	public byte nthreads;
	/**
	 * the number of threads to use internally (1)<br>
	 * C type : blosc2_sheader*
	 */
	public Sheader.ByReference schunk;
	public ContextDparams() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("nthreads", "schunk");
	}
	/**
	 * @param schunk the number of threads to use internally (1)<br>
	 * C type : blosc2_sheader*
	 */
	public ContextDparams(byte nthreads, Sheader.ByReference schunk) {
		super();
		this.nthreads = nthreads;
		this.schunk = schunk;
	}
	public ContextDparams(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected ContextDparams newInstance() { return new ContextDparams(); }
	public static ContextDparams[] newArray(int arrayLength) {
		return Structure.newArray(ContextDparams.class, arrayLength);
	}
	public static class ByReference extends ContextDparams implements Structure.ByReference {
		
	};
	public static class ByValue extends ContextDparams implements Structure.ByValue {
		
	};
}
